### ISSUE TITLE
Implement parallel collect

### ISSUE THREAD

**Issue by edre** [rayon-rs/rayon-hash#17]
To mirror the functionality of parallel produce, this crate should support parallel collect into a std-like hash table.

I have a proposed design.
Phase 1: In parallel, hash keys and partition entries into N shards, where N >= num CPUs.
  The intermediate format is a Vec<LinkedList<Vec<T>>>, so that each shard is concatenated efficiently during Fold.

Phase 2: Allocate destination to expected size.

Phase 3: For each shard in parallel, insert elements into that section of the table.
  Elements that would round-robin off the end of the shard get stored in an overflow list instead.

Phase 4: For each shard in parallel, insert overflow elements from the previous shard.

This construction requires 3 synchronization points, but the last phase should be pretty small and fast. This could be extended to support parallel write to an existing hashmap, but would need special logic to add from both sources during a resize.

**Comment by edre** [comment]
s/round-robin/robin-hood/

**Comment by cuviper** [comment]
It sounds pretty cool if you can actually make that work.  To the extent that it may require changes in the "upstream" code, please try to isolate this such that merging changes from `std` won't be too painful.

**Comment by edre** [comment]
I discovered a wrinkle in my algorithm.
In order to know how to partition elements into contiguous shards, you need to know the final capacity of the destination table. This requires estimating the number of (unique) keys. I think this would prevent using an unsized producer, unless we add another phase to just count elements.

An alternative would be to rearchitect how hashing works, by reversing the bits of the hash (after masking). In this way, the LSB of the hash determines the MSB of the address and so on. Thus you can partition the items in to N=2^k shards regardless of the final capacity of the table. Unfortunately, I don't think this is a cheap operation, but it would involve only modifying a small amount of upstream code.

**Comment by edre** [comment]
Or instead of reversing the bits, you just use the upper C bits for the capacity_mask instead of the lower C bits. The parallel shard assigner looks at the top S bits. This only adds one operation to the existing lookup code, and should be easier to reason about.

**Comment by cuviper** [comment]
Closing per https://github.com/rayon-rs/rayon-hash/pull/19#issuecomment-486483033
